### ISSUE TITLE
IGAMT Delta Feature does not represent the cardinalities accurately

### ISSUE THREAD

**Issue by Healthedata1** [haffonist/igamt#963] opened 2016-12-15 00:06 UTC
IGAMT Delta Feature does not represent the cardinalities ( min and max) accurately per the published base. Please fix

**Comment by haffonist** [comment] 2016-12-15 15:32
@IsmailMellouli any idea ?

**Comment by IsmailMellouli** [comment] 2016-12-15 18:06
What object are you comparing, Datatype or segment?

**Comment by RikiMerrick** [comment] 2016-12-21 22:59
we were comparing segments - specifically OBX and OBR

**Comment by RikiMerrick** [comment] 2016-12-21 23:26
see example screenshot for OBX segment from v2.8.2:
![obxsegment cardinalities](https://cloud.githubusercontent.com/assets/22180804/21409894/e3e6b4ee-c791-11e6-903b-fd9055f50747.JPG)

**Comment by haffonist** [comment] 2016-12-22 14:48
The issue is not with the delta feature but with the source data. Other users have reported this and we are working on fixing this.  We will keep  you posted.  I will close this ticket since it is not the delta issue but the data issue.

**Closed by haffonist** 2016-12-22 14:48 UTC

**Comment by RikiMerrick** [comment] 2016-12-22 16:14
thanks for the note

Riki Merrick
Vernetzt, LLC
rikimerrick@gmail.com
cell: 916.216.0052
skype: riki.merrick
