### ISSUE TITLE
nested segment groups missing

### ISSUE THREAD

**Issue by csnewman88** [haffonist/igamt#1101] opened 2017-01-16 03:48 UTC
The Word export doesn't seem to include segment groups that are nested in other segment groups. Not only are the segment groups (and the segments in them) not in the message definition table, the segments are also not included following the message definition table in the verbose format

For example, in the screen shot below, there are first level segment groups (like insurance (green arrow)) and second level segment groups (timing and observation within the Order segment group (red arrow))

![image](https://cloud.githubusercontent.com/assets/17408249/21970408/95792d26-db6b-11e6-9ba0-57dc846b9fca.png)

The insurance segment group is in the export (green arrow below) but neither Timing nor Observation (red arrows).

![image](https://cloud.githubusercontent.com/assets/17408249/21970460/2d14c668-db6c-11e6-9cc1-0d9f0138de57.png)

**Comment by maxence-lefort** [comment] 2017-01-17 17:13
Hi @csnewman88 the first issue is fixed, but about the verbose export not showing the segments within the groups, I can't reproduce the issue. We decided to only show the segments once so if a segment is both in a group and anywhere else, it's going to be displayed only once in the message segments. Can you confirm that it's not exported at all?
Thanks

**Comment by maxence-lefort** [comment] 2017-01-17 17:24
@csnewman88 here is what it looks like on my end, all the segments seem to be exported
![screen shot 2017-01-17 at 12 18 29 pm](https://cloud.githubusercontent.com/assets/13853131/22031775/bf4aff22-dcaf-11e6-8474-1f864496c9e4.png)

**Comment by csnewman88** [comment] 2017-01-17 17:33
The IG is internally consistent, but the IG doesn't reflect what is in IGAMT.

This is what is in IGAMT:
![image](https://cloud.githubusercontent.com/assets/17408249/22032080/93fa8380-dca8-11e6-8db9-d354599e2a7d.png)

Note that there are 3 segments (and this the first instance if OBX_IZ_01) after RXR and none of these are present in either the VXU message definition table (the right hand portion of your image) or in the sections (the left hand portion of your image).

**Comment by haffonist** [comment] 2017-01-17 21:30
Craig,

This is now fixed on the dev site. Can you please confirm: https://hit-dev.nist.gov:8088/igamt/#/ig ?


Thanks


________________________________

**Closed** 2017-01-19 21:17 UTC
Labels: bug, urgent
