### ISSUE TITLE
BUG in changing DT flavor extension

### ISSUE THREAD

**Issue by robnist** [haffonist/igamt#1974] opened 2017-07-10 16:40 UTC
I created a new DT flavor, then wanted to change the extension and here is the error message i got....

![image](https://user-images.githubusercontent.com/14874904/28029104-d7d7fd06-656c-11e7-8225-554d22f5226c.png)

**Comment by afrold** [comment] 2017-07-10 17:00
I can't reproduce, I think you clicked on a different button previously. I am closing this now.  Please reopen if issue persist.

**Closed as completed by afrold** 2017-07-10 17:00 UTC
