### ISSUE TITLE
Usage not showing up in Profile Component

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#1307] opened 2017-02-21 21:04 UTC
I get a drop down box, I can select a "different" usage, but the original and the new usages do not show up. 
![igamt pc 1](https://cloud.githubusercontent.com/assets/13591511/23184872/65b28852-f84f-11e6-9856-5e53b9e247b3.JPG)

**Comment by haffonist** [comment] 2017-02-21 21:05
This is duplicate of #1053.

**Closed by haffonist** 2017-02-21 21:05 UTC
