### ISSUE TITLE
Export: Extra lines are added

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#1339] opened 2017-03-02 20:54 UTC
It appears that two line feeds, and one end of paragraph marker are added for each row.  It would be better to omit the two line feeds.

![linefeed](https://cloud.githubusercontent.com/assets/14842422/23526548/6fa496da-ff60-11e6-8c7f-a17c8940cf92.png)

**Comment by maxence-lefort** [comment] 2017-03-03 15:55
Duplicate of #1160

**Closed by maxence-lefort** 2017-03-03 15:55 UTC
Labels: enhancement
